modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/BYG/issues"
[[mods]]
modId = "biomes3d"
version = "1.0"
displayName = "3D Biomes"
displayURL = ""
logoFile = "logo_text.png"
credits = "N/A"
authors = "Corgi Taco"
description = '''
A mod adding 3D Biomes!
'''
[[dependencies.3dbiomes]]
modId = "forge"
mandatory = true
versionRange = "[34.1.42,)"
ordering = "NONE"
side = "BOTH"